### ISSUE TITLE
Value should be string

### ISSUE THREAD

**Issue by kotoulasphilip** [vueform/plugin-mask#1]
### Environment

@vueform/vueform:  1.9.2
@vueform/plugin-mask: 1.0.3
@vite: 5.0.2

### Reproduction

 To reproduce the error just try load a number to a textElement with mask

### Describe the bug

The mask breaks my code with the error 'Error: value should be a string' when I attempt to load a number into the TextElement. I believe it would be beneficial to accept numbers as well, not just strings, since backend systems typically return numbers.

for example I tried to load a number (eg 40000) in this element:

        <TextElement
          name="price"
          label="Price"
          :mask="{
            mask: 'number',
            thousandsSeparator: '.', // any single char
            scale: 0, // digits after fractional delimiter, 0 for integers
          }"
        />

**Comment by thely** [comment]
I also get this error, but I'm getting it when I try to change other dropdowns on my form that recompute computed variables.

**Comment by adamberecz** [comment]
Thanks for reporting the issue - it should now be fixed in `1.0.4`
